### PR TITLE
Docker Setup for backend api

### PR DESCRIPTION
**Pull request by gsundeep-tech**
Description:

Added the docker image to run the backend API locally

### CODE REVIEW

**Review by vigneshgowrabathuni — APPROVED** [review]
Looks Good!

**Comment by gsundeep-tech** [comment]
@vigneshgowrabathuni  please review, configuration changes are also added and thoroughly tested.

**Comment by gsundeep-tech** [comment]
@vigneshgowrabathuni please review, configuration changes are also added and thoroughly tested.

**Review by vigneshgowrabathuni — APPROVED** [review]
Looks good 👍🏻

**Pull request merged**
